apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels: myapp1
  namespace: default
spec:
  replicas: 2
  selector:
    matchLables:
      app: myapp1
  template:
    metadata:
      labels:
        app: myapp1
    spec:
      containers:
      - name: version1
        image: sri3050/myapp:v2
        ports:
        - containerPort: 80
